[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' https://unpkg.com;
      connect-src 'self' https://*.supabase.co wss://*.supabase.co https://prod.spline.design;
      style-src 'self' 'unsafe-inline';
      img-src 'self' https: data: blob:;
      font-src 'self' https:;
      frame-src 'self' https:;
      object-src 'none';
      base-uri 'self';
      form-action 'self';
    """

