[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self';
      connect-src 'self' https://yiiarlagxlrzzomzpqid.supabase.co wss://yiiarlagxlrzzomzpqid.supabase.co https://prod.spline.design;
      script-src 'self' 'unsafe-inline';
      style-src 'self' 'unsafe-inline';
      img-src 'self' data: blob: https:;
      font-src 'self' https:;
      frame-src https:;
    """
